import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import {  StateContext } from "../Context/StateContext";
import  { Toaster } from 'react-hot-toast'








export const metadata: Metadata = {
  title: "E-Commerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StateContext>
        <body>
        <Toaster/>
          <Navbar/>
          {children}
          <Footer/>
          </body>
      </StateContext>
    </html>
  )
}
